# This is a basic workflow to help you get started with Actions
name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Assume AWS Role
        with:
          role-to-assume: arn:aws:iam::820242941495:role/samplegithubrole #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ap-south-1
          
      - name: Deploy to S3
        run: |
          aws s3 sync ./index.html s3://samplehelloworldapp
